from __future__ import annotations

import json
from pathlib import Path

from lxml import html


ROOT = Path(__file__).resolve().parents[1]
PATH = ROOT / "foundation-crawlspace-waterproofing-contractors" / "index.html"
URL = "https://local.refrdai.com/foundation-crawlspace-waterproofing-contractors/"
BOOKING = "https://calendar.app.google/qwZB5sgoY74tPssA6"
FORM_ID = "b972ec68-3a3b-47f8-b97d-d07a1e077474"
PORTAL_ID = "49371050"
FORM_FALLBACK = "https://te6y2.share.hsforms.com/2uXLsaDo7R_i5fdB6Hgd0dA"


FAQS = [
    ("Is this only for foundation-repair companies?", "No. It is for independent foundation-repair, crawl-space, and basement-waterproofing contractors in the United States. The first build still focuses on one primary service."),
    ("What does the 30-mile build include?", "The $3,400 build covers one primary service and the final list of eligible towns you approve within an agreed 30-mile radius, up to 100. Every included town receives one main town-and-service page plus two original town-specific customer-question pages."),
    ("What does the initial build cost?", "The one-time initial investment is $3,400: $1,700 to begin and $1,700 after staging approval, before launch."),
    ("Will this replace my current website?", "No. The new customer-owned territory website runs alongside your current site."),
    ("Is the $500 monthly expansion required?", "No. It is separate, optional, may be offered around month three only when enough usable search-performance data exists, and never starts automatically."),
    ("Does REFRDAI guarantee rankings, inquiries, or revenue?", "No. REFRDAI does not guarantee indexing, rankings, inquiries, calls, estimates, projects, contracts, or revenue."),
    ("How does REFRDAI handle territory conflicts?", "Before recommending a build, REFRDAI checks the proposed service, center, 30-mile radius, and final town list for overlap with active engagements. A review does not reserve a territory. Protection begins only after agreement acceptance and initial payment."),
    ("Do I have to pay each year to keep the website or domain?", "No. You own and keep both. The optional $495 Territory Continuity Review includes the applicable domain renewal for that term and may renew territory protection after review and written renewal. If you decline it, protection expires and you pay the registrar directly for future domain renewal."),
    ("Can REFRDAI cover more than 30 miles?", "Yes. Larger territories, inventories above 100 communities, and additional primary services require separate scope and pricing."),
    ("Is managed hosting included?", "Yes, under normal usage. Unlimited hosting is not promised."),
]


doc = html.parse(str(PATH))
root = doc.getroot()


def set_text(xpath: str, value: str) -> None:
    nodes = root.xpath(xpath)
    if not nodes:
        raise RuntimeError(f"Missing metadata node: {xpath}")
    nodes[0].text = value


def set_attr(xpath: str, name: str, value: str) -> None:
    nodes = root.xpath(xpath)
    if not nodes:
        raise RuntimeError(f"Missing metadata node: {xpath}")
    nodes[0].set(name, value)


set_text("//title", "Foundation and Waterproofing Contractor Territory Websites | REFRDAI")
set_attr("//meta[@name='description']", "content", "A customer-owned territory website for foundation-repair, crawl-space, and basement-waterproofing contractors pursuing projects in more towns.")
set_attr("//meta[@property='og:title']", "content", "Territory Websites for Foundation and Waterproofing Contractors")
set_attr("//meta[@property='og:description']", "content", "Make one foundation, crawl-space, or basement-waterproofing service easier for homeowners to find and understand across your service area.")
set_attr("//meta[@name='twitter:title']", "content", "Territory Websites for Foundation and Waterproofing Contractors")
set_attr("//meta[@name='twitter:description']", "content", "Help homeowners in more towns find and contact your company for one primary structural or water-control service.")

schema = {
    "@context": "https://schema.org",
    "@graph": [
        {"@type": "WebPage", "@id": URL + "#webpage", "url": URL, "name": "Territory websites for foundation, crawl-space, and basement-waterproofing contractors", "description": "A REFRDAI offer for independent foundation-repair, crawl-space, and basement-waterproofing contractors in the United States.", "inLanguage": "en-US", "isPartOf": {"@id": "https://local.refrdai.com/#website"}, "about": {"@id": URL + "#service"}, "breadcrumb": {"@id": URL + "#breadcrumb"}},
        {"@type": "BreadcrumbList", "@id": URL + "#breadcrumb", "itemListElement": [
            {"@type": "ListItem", "position": 1, "name": "REFRDAI Local", "item": "https://local.refrdai.com/"},
            {"@type": "ListItem", "position": 2, "name": "Industries", "item": "https://local.refrdai.com/industries/"},
            {"@type": "ListItem", "position": 3, "name": "Foundation and Waterproofing Contractors", "item": URL},
        ]},
        {"@type": "Service", "@id": URL + "#service", "name": "REFRDAI territory website for foundation and waterproofing contractors", "description": "A $3,400 customer-owned territory website for one primary foundation, crawl-space, or basement-waterproofing service within an agreed 30-mile radius.", "serviceType": "Customer-owned territory website build", "provider": {"@id": "https://refrdai.com/#organization"}, "areaServed": {"@type": "Country", "name": "United States"}, "offers": {"@type": "Offer", "price": "3400", "priceCurrency": "USD", "description": "One-time initial build. $1,700 to begin and $1,700 after staging approval, before launch."}},
        {"@type": "FAQPage", "mainEntity": [
            {"@type": "Question", "name": q, "acceptedAnswer": {"@type": "Answer", "text": a}}
            for q, a in FAQS
        ]},
    ],
}
scripts = root.xpath("//script[@type='application/ld+json']")
if not scripts:
    raise RuntimeError("Missing JSON-LD script")
scripts[0].text = json.dumps(schema, ensure_ascii=False, separators=(",", ":"))

dots = "".join(f'<span class="city-dot d{i}"></span>' for i in range(1, 26))
faq_cards = "".join(f'<article class="faq"><h3>{q}</h3><p>{a}</p></article>' for q, a in FAQS)

body_markup = f'''<body data-industry="foundation-crawlspace-waterproofing">
<a class="skip" href="#main">Skip to main content</a>
<nav><div class="container nav-inner"><a class="brand" href="/"><span class="brand-mark" aria-hidden="true">RD</span><span><span>REFR</span>DAI · Local</span></a><div class="nav-links"><a href="/industries/">Industries</a><a href="#how-it-works">How It Works</a><a href="#investment">Investment</a><a class="btn btn-primary" data-track="primary-cta" href="#territory-review">Request My Free 15-Minute Territory Review</a></div></div></nav>
<header class="hero"><div class="container hero-grid"><div><p class="eyebrow">For independent foundation, crawl-space, and basement-waterproofing contractors</p><h1>Be easier to find for the structural or water-control projects you want in more towns you serve.</h1><p class="hero-summary">REFRDAI builds a separate website your company owns alongside its current site. The first build focuses on one primary service. Each approved town receives a dedicated service page and two original customer-question pages, with clear ways for homeowners to call or request an estimate.</p><div class="hero-actions"><a class="btn btn-primary" data-track="primary-cta" href="#territory-review">Request My Free 15-Minute Territory Review</a><a class="btn btn-secondary" href="#build-scope">See What the Build Includes</a></div><p class="expectation">The 15-minute review is free. The initial build costs $3,400 if you choose to proceed. REFRDAI does not guarantee rankings, inquiries, projects, contracts, or revenue.</p></div><aside class="map-card" role="img" aria-label="Illustration of an agreed 30-mile territory with eligible approved communities"><div class="map-top"><b>Illustrative 30-mile territory</b><span>Approved before production</span></div><div class="territory"><span class="center-dot">Agreed<br>center</span>{dots}<span class="radius-label">30 miles</span><span class="coverage-label">Up to 100 eligible approved communities</span></div><p class="map-note">The map is an example only. Your center, eligible communities, and exact initial page count are approved before production.</p></aside></div></header>
<div class="signal-row"><div class="container signals"><div class="signal"><strong>One primary service</strong><span>Choose the foundation, crawl-space, or waterproofing work the first build should support.</span></div><div class="signal"><strong>One agreed 30-mile radius</strong><span>Include every eligible approved community, up to 100.</span></div><div class="signal"><strong>Done for you</strong><span>Planning, production, staging, launch setup, and managed hosting under normal usage.</span></div></div></div>
<main id="main">
<section id="who-it-is-for"><div class="container"><p class="kicker">Choose the work</p><h2 class="section-title">Choose the project path that matters most to your company.</h2><p class="section-copy">Your company may offer several related services. The $3,400 initial build focuses on one primary service so every page can answer a clear homeowner need.</p><div class="audience-grid"><article class="card"><div class="icon">F</div><h3>Foundation repair</h3><p>For companies helping homeowners evaluate settlement, cracks, movement, stabilization, structural repair, or another verified foundation concern.</p></article><article class="card"><div class="icon">C</div><h3>Crawl-space services</h3><p>For companies providing encapsulation, moisture control, drainage, insulation, structural repair, or another defined crawl-space service.</p></article><article class="card"><div class="icon">B</div><h3>Basement waterproofing</h3><p>For contractors addressing basement water entry, drainage, moisture, wall or floor concerns, and related waterproofing needs.</p></article></div><p class="fit-note">The company may offer all three categories. The first territory website still begins with one agreed primary service.</p></div></section>
<section class="panel" id="territory-opportunity-review"><div class="container"><p class="kicker">Free 15-minute review</p><h2 class="section-title">Which towns matter for the work you want?</h2><p class="section-copy">In 15 minutes, William Smith will compare the towns you serve with where your company appeared more or less clearly in the public searches reviewed. You can correct the map, choose one service-and-town priority, and decide whether a separate territory website deserves a closer look.</p><div class="review-grid"><div class="agenda"><div class="agenda-item"><span class="agenda-num">01</span><div><strong>Where homeowners can already find you</strong><span>Review towns where the business already has a clear path into the agreed service.</span></div></div><div class="agenda-item"><span class="agenda-num">02</span><div><strong>Towns worth checking</strong><span>Identify communities that may deserve a closer look without treating public search observations as proof of demand.</span></div></div><div class="agenda-item"><span class="agenda-num">03</span><div><strong>The service that matters most</strong><span>Choose one foundation, crawl-space, or waterproofing service for the first build.</span></div></div><div class="agenda-item"><span class="agenda-num">04</span><div><strong>Whether the build fits</strong><span>Decide whether to explore the customer-owned territory website or stop with no obligation.</span></div></div></div><aside class="prep"><h3>Bring three things</h3><ul><li>Your company website</li><li>The one service you most want the first build to support</li><li>The towns, counties, or territory center you want to review</li></ul><a class="btn btn-primary" data-track="primary-cta" href="#territory-review">Request My Free 15-Minute Territory Review</a></aside></div></div></section>
<section id="build-scope"><div class="container"><p class="kicker">The initial build</p><h2 class="section-title">One focused website covering the towns you approve.</h2><p class="section-copy">The $3,400 build covers one primary service within an agreed 30-mile radius from one center. It includes the final list of eligible towns you approve, up to 100. Actual counts vary. A town is included only when it can support a useful, locally relevant page for the agreed service.</p><div class="model-grid"><div class="formula"><div class="formula-box"><strong>1</strong><span>included town</span></div><div class="plus">+</div><div class="formula-box"><strong>1</strong><span>main town-and-service page</span></div><div class="plus">+</div><div class="formula-box"><strong>2</strong><span>original town-specific question pages</span></div></div><aside class="scope-card"><h3>Initial build scope</h3><ul class="scope-list"><li>One primary service.</li><li>One agreed 30-mile radius from one center.</li><li>The final list of eligible towns you approve, up to 100.</li><li>Three original pages for every included town.</li><li>Staging review before final payment and launch.</li><li>Managed hosting under normal usage.</li><li>A completed website and domain the client owns and keeps.</li><li>One-client-at-a-time protection during the active protection term.</li></ul></aside></div><p class="fit-note"><strong>What makes a town eligible?</strong> It must be a real community within the company’s practical service area and support a useful, locally relevant page for the agreed service. The final town list you approve records the exact initial scope.</p></div></section>
<section class="panel"><div class="container"><p class="kicker">Homeowner decisions</p><h2 class="section-title">Different symptoms lead to different project decisions.</h2><p class="section-copy">A homeowner noticing a foundation crack, a damp crawl space, or water entering a basement is not making the same decision. The first territory build focuses on one service and answers the questions that help that homeowner decide whether to request an inspection or estimate.</p><div class="audience-grid"><article class="card"><h3>Foundation concern</h3><p>Explain the visible concern, the limits of online information, what the contractor evaluates, and how the homeowner requests the next step.</p></article><article class="card"><h3>Crawl-space concern</h3><p>Explain moisture, odor, insulation, drainage, wood, structure, or comfort concerns only within the contractor’s actual service scope.</p></article><article class="card"><h3>Basement-water concern</h3><p>Explain where and when water appears, what the owner should document, and why a property-specific evaluation comes before a correction.</p></article></div><p class="fit-note">The website will not diagnose a structure, recommend a repair without evidence, invent local conditions, or promise a project outcome.</p></div></section>
<section id="what-is-included"><div class="container"><p class="kicker">Done for you</p><h2 class="section-title">A complete territory website your company does not have to operate.</h2><p class="section-copy">REFRDAI handles the agreed build from planning through staging and launch setup.</p><div class="deliverables"><article class="deliverable"><span>01</span><h3>Plan the service and territory</h3><p>Approve one primary service, the radius center, and the complete list of towns included in the build.</p></article><article class="deliverable"><span>02</span><h3>Build the town pages</h3><p>Create one main service page and two original customer-question pages for every approved town.</p></article><article class="deliverable"><span>03</span><h3>Review the staged website</h3><p>Review the completed staging build before the second payment and public launch.</p></article><article class="deliverable"><span>04</span><h3>Launch and host</h3><p>REFRDAI completes launch setup and provides managed hosting under normal usage.</p></article></div></div></section>
<section class="panel" id="investment" data-qa-shared="true"><div class="container"><p class="kicker">Clear investment</p><h2 class="section-title">Know the full initial price before you book.</h2><p class="section-copy">The Territory Opportunity Review is free. If the project fits and you choose to proceed, the customer-owned territory website costs $3,400.</p><div class="investment-grid"><article class="price-card"><span class="price-label">One-time initial build</span><div class="price">$3,400</div><p class="price-copy">One primary service within one agreed 30-mile radius, covering every eligible approved community up to 100.</p><div class="split"><div><strong>$1,700</strong><span>To begin production</span></div><div><strong>$1,700</strong><span>After staging approval, before launch</span></div></div></article><div class="optional-stack"><article class="optional"><span>Optional after the first year</span><h3>$495 Territory Continuity Review</h3><p>Includes the applicable domain renewal for that term, a scope and conflict review, and written renewal of the approved protected territory. If declined, you still own the site and domain, protection expires, and you pay the registrar directly for future renewal.</p></article><article class="optional"><span>Separate and never automatic</span><h3>Possible $500-per-month expansion</h3><p>May be offered around month three only when enough usable search-performance data exists. It is optional, promises no fixed page count, and never starts automatically.</p></article><article class="optional"><span>Your company controls the domain</span><h3>First year included</h3><p>REFRDAI registers and pays for year one, then transfers the domain after launch and cleared final payment as soon as the registrar permits.</p></article></div></div><p class="fit-note">The first protected-territory term runs for 12 months from public launch. Larger radiuses, inventories above 100 communities, and additional services require separate scope and pricing.</p></div></section>
<section id="how-it-works"><div class="container"><p class="kicker">Simple process</p><h2 class="section-title">From territory review to public launch.</h2><div class="steps"><article class="step"><span>1</span><h3>Review the territory</h3><p>Discuss the primary service, territory center, target towns, and current website.</p></article><article class="step"><span>2</span><h3>Confirm the scope</h3><p>Approve the 30-mile boundary and exact eligible-community inventory.</p></article><article class="step"><span>3</span><h3>Build and stage</h3><p>REFRDAI produces the agreed town-and-service pages and customer-question pages.</p></article><article class="step"><span>4</span><h3>Approve and launch</h3><p>After staging approval and the second payment, REFRDAI completes launch setup.</p></article></div></div></section>
<section class="panel" id="expectations"><div class="container"><p class="kicker">Straight expectations</p><h2 class="section-title">Clear work. Clear limits.</h2><div class="expectations"><article class="expect-card yes"><h3>What REFRDAI does</h3><p>Plans and builds the customer-owned territory website, creates the included town pages, provides staging review, completes launch setup, provides managed hosting under normal usage, and checks for an active territory conflict before recommending overlapping work.</p></article><article class="expect-card no"><h3>What REFRDAI does not promise</h3><p>Indexing, search rankings, inquiries, calls, estimates, projects, contracts, revenue, market share, or any other customer or business outcome.</p></article></div><div class="founder"><div class="founder-mark">WS</div><div><h3>Your review is with William Smith.</h3><p>William is the founder of REFRDAI. He will review the service and territory, explain the customer-owned website in plain language, and tell you when the proposed build does not appear to fit. The review creates no purchase obligation.</p></div></div></div></section>
<section id="faq"><div class="container"><p class="kicker">Before the review</p><h2 class="section-title">Foundation and waterproofing contractor questions.</h2><p class="section-copy">Useful details before you decide whether to book.</p><div class="faq-grid">{faq_cards}</div></div></section>
<section class="form-section panel" id="territory-review" data-qa-shared="true"><div class="container form-grid"><div class="form-copy"><p class="kicker">Free 15-minute review</p><h2 class="section-title">Choose a time to review your service territory.</h2><p class="section-copy">Share your company name, company website, email, and the towns or counties you want to review. Phone is optional. After submission, choose an available Google Meet time.</p><div class="review-details"><div class="review-detail"><b>Meeting</b><span>15-minute Google Meet</span></div><div class="review-detail"><b>Review</b><span>Free, with no purchase obligation</span></div><div class="review-detail"><b>Build price</b><span>$3,400 only if you choose to proceed</span></div><div class="review-detail"><b>Prepare</b><span>Company website, primary service, and target towns or counties</span></div></div><p class="privacy">Your information is used to prepare and coordinate the review. Submitting the form does not authorize a purchase, automatic outreach, or enrollment.</p></div><div class="form-card"><h2>Request My Free 15-Minute Territory Review</h2><p>Complete the short intake, then choose an available Google Meet time.</p><script src="https://js.hsforms.net/forms/embed/{PORTAL_ID}.js" defer></script><div class="hs-form-frame" data-region="na1" data-form-id="{FORM_ID}" data-portal-id="{PORTAL_ID}"></div><noscript><p>JavaScript is required to load the intake form.</p></noscript><a class="form-fallback" href="{FORM_FALLBACK}" rel="nofollow">Open the Secure Intake Form in a New Page</a></div></div><div class="container booking-panel" data-booking-panel aria-hidden="true"><h2>Choose Your 15-Minute Google Meet Time</h2><p>Your intake is complete. Select an available time below or open the appointment schedule directly.</p><iframe title="REFRDAI Territory Opportunity Review appointment schedule" src="https://calendar.google.com/calendar/appointments/schedules/AcZssZ1fwLrsT8h5hUpuPgocpDpCS03L1MffWm7y7NrTNXQvR9CJed1FLZO61eQYjJrH6TivZqysSG2F?gv=true"></iframe><a class="btn btn-primary" data-booking-link href="{BOOKING}" target="_blank" rel="noopener">Open the Google Appointment Schedule</a></div></section>
</main>
<footer><div class="container footer-inner"><span>© 2026 REFRDAI Local. Customer-owned territory websites for local service businesses.</span><div class="footer-links"><a href="/">Home</a><a href="/industries/">Industries</a><a href="/entity-source-of-truth/">Definitions</a><a href="/insights/">Insights</a></div></div></footer>
<script src="/assets/industry-pages.js" defer></script>
</body>'''

new_body = html.fromstring(body_markup)
old_body = root.xpath("//body")[0]
old_body.getparent().replace(old_body, new_body)

output = html.tostring(root, encoding="unicode", method="html", doctype="<!doctype html>")
PATH.write_text(output + "\n", encoding="utf-8", newline="\n")
print(f"Rewrote copy: {PATH}")
